---
title: "Hyebeen's Flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(ggplot2)
library(tidyverse)
library(plotly)
library(leaflet)
library(sp)
library(flexdashboard)
library(shiny)
library(shinydashboard)
```

```{r}
# Load required packages
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(dslabs))
view(gapminder)
```

```{r}
gapminder_cat <- gapminder %>%
mutate(
  year_cat = as.factor(year)
  )
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
kim <- gapminder %>%
ggplot() +
geom_histogram(mapping = aes(x = infant_mortality, fill = continent), bins = 30)+
labs(
title = "A histogram of infant_mortality",
x = "infant_mortality")

ggplotly(kim)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
kim_1 <- gapminder %>%
ggplot()+
geom_point (
mapping = aes(
x = life_expectancy,
y = infant_mortality, color = continent
)
) +
labs(
title = "A scatter plot of life_expectancy_andinfant_mortality",
x = "life_expectancy" ,
y = "infant_mortality"
)

ggplotly(kim_1)
```

### Chart C

```{r}
kime_2 <- gapminder_cat %>%
  filter(year %% 10 == 0) %>%
  ggplot() +
  geom_histogram(
    mapping = aes(
      x = life_expectancy,
      color = year_cat
    ),
    bins = 20
  ) +
  facet_wrap(~ continent) +
   labs(
    title = "Increasing life expectancy over time in the world",
    x = "life expectancy",
    )

ggplotly(kime_2)
```

